[project]
name = "long-context-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.141.0",
    "crewai-tools>=0.51.1",
    "mcp>=1.11.0",
]
